# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tunix/experimental/distributed/examples/rl/service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tunix/experimental/distributed/examples/rl/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8tunix/experimental/distributed/examples/rl/service.proto\x12\x17\x65xamples.distributed.rl\"!\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"&\n\x10GenerateResponse\x12\x12\n\ncompletion\x18\x01 \x01(\t\"2\n\x0cTrainRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\ncompletion\x18\x02 \x01(\t\" \n\rTrainResponse\x12\x0f\n\x07weights\x18\x01 \x01(\t2q\n\x0eRolloutService\x12_\n\x08Generate\x12(.examples.distributed.rl.GenerateRequest\x1a).examples.distributed.rl.GenerateResponse2h\n\x0eTrainerService\x12V\n\x05Train\x12%.examples.distributed.rl.TrainRequest\x1a&.examples.distributed.rl.TrainResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tunix.experimental.distributed.examples.rl.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=85
  _globals['_GENERATEREQUEST']._serialized_end=118
  _globals['_GENERATERESPONSE']._serialized_start=120
  _globals['_GENERATERESPONSE']._serialized_end=158
  _globals['_TRAINREQUEST']._serialized_start=160
  _globals['_TRAINREQUEST']._serialized_end=210
  _globals['_TRAINRESPONSE']._serialized_start=212
  _globals['_TRAINRESPONSE']._serialized_end=244
  _globals['_ROLLOUTSERVICE']._serialized_start=246
  _globals['_ROLLOUTSERVICE']._serialized_end=359
  _globals['_TRAINERSERVICE']._serialized_start=361
  _globals['_TRAINERSERVICE']._serialized_end=465
# @@protoc_insertion_point(module_scope)
