# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tunix.experimental.distributed.examples.rl import service_pb2 as tunix_dot_experimental_dot_distributed_dot_examples_dot_rl_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tunix/experimental/distributed/examples/rl/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RolloutServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/examples.distributed.rl.RolloutService/Generate',
                request_serializer=tunix_dot_experimental_dot_distributed_dot_examples_dot_rl_dot_service__pb2.GenerateRequest.SerializeToString,
                response_deserializer=tunix_dot_experimental_dot_distributed_dot_examples_dot_rl_dot_service__pb2.GenerateResponse.FromString,
                _registered_method=True)


class RolloutServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RolloutServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=tunix_dot_experimental_dot_distributed_dot_examples_dot_rl_dot_service__pb2.GenerateRequest.FromString,
                    response_serializer=tunix_dot_experimental_dot_distributed_dot_examples_dot_rl_dot_service__pb2.GenerateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'examples.distributed.rl.RolloutService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('examples.distributed.rl.RolloutService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RolloutService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/examples.distributed.rl.RolloutService/Generate',
            tunix_dot_experimental_dot_distributed_dot_examples_dot_rl_dot_service__pb2.GenerateRequest.SerializeToString,
            tunix_dot_experimental_dot_distributed_dot_examples_dot_rl_dot_service__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TrainerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Train = channel.unary_unary(
                '/examples.distributed.rl.TrainerService/Train',
                request_serializer=tunix_dot_experimental_dot_distributed_dot_examples_dot_rl_dot_service__pb2.TrainRequest.SerializeToString,
                response_deserializer=tunix_dot_experimental_dot_distributed_dot_examples_dot_rl_dot_service__pb2.TrainResponse.FromString,
                _registered_method=True)


class TrainerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Train': grpc.unary_unary_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=tunix_dot_experimental_dot_distributed_dot_examples_dot_rl_dot_service__pb2.TrainRequest.FromString,
                    response_serializer=tunix_dot_experimental_dot_distributed_dot_examples_dot_rl_dot_service__pb2.TrainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'examples.distributed.rl.TrainerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('examples.distributed.rl.TrainerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/examples.distributed.rl.TrainerService/Train',
            tunix_dot_experimental_dot_distributed_dot_examples_dot_rl_dot_service__pb2.TrainRequest.SerializeToString,
            tunix_dot_experimental_dot_distributed_dot_examples_dot_rl_dot_service__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
