# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tunix.experimental.distributed.runtime.discovery import discovery_service_pb2 as tunix_dot_experimental_dot_distributed_dot_runtime_dot_discovery_dot_discovery__service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tunix/experimental/distributed/runtime/discovery/discovery_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DiscoveryServiceStub:
    """Discovery service used by distributed workers to register their coordinates.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/tunix.experimental.distributed.runtime.discovery.DiscoveryService/Register',
                request_serializer=tunix_dot_experimental_dot_distributed_dot_runtime_dot_discovery_dot_discovery__service__pb2.RegisterRequest.SerializeToString,
                response_deserializer=tunix_dot_experimental_dot_distributed_dot_runtime_dot_discovery_dot_discovery__service__pb2.RegisterResponse.FromString,
                _registered_method=True)


class DiscoveryServiceServicer:
    """Discovery service used by distributed workers to register their coordinates.
    """

    def Register(self, request, context):
        """Registers a worker node with the discovery service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=tunix_dot_experimental_dot_distributed_dot_runtime_dot_discovery_dot_discovery__service__pb2.RegisterRequest.FromString,
                    response_serializer=tunix_dot_experimental_dot_distributed_dot_runtime_dot_discovery_dot_discovery__service__pb2.RegisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tunix.experimental.distributed.runtime.discovery.DiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tunix.experimental.distributed.runtime.discovery.DiscoveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiscoveryService:
    """Discovery service used by distributed workers to register their coordinates.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tunix.experimental.distributed.runtime.discovery.DiscoveryService/Register',
            tunix_dot_experimental_dot_distributed_dot_runtime_dot_discovery_dot_discovery__service__pb2.RegisterRequest.SerializeToString,
            tunix_dot_experimental_dot_distributed_dot_runtime_dot_discovery_dot_discovery__service__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
