# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tunix/experimental/distributed/runtime/discovery/discovery_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tunix/experimental/distributed/runtime/discovery/discovery_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHtunix/experimental/distributed/runtime/discovery/discovery_service.proto\x12\x30tunix.experimental.distributed.runtime.discovery\"C\n\x0fRegisterRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x10\n\x08metadata\x18\x03 \x01(\x0c\"\x12\n\x10RegisterResponse2\xa6\x01\n\x10\x44iscoveryService\x12\x91\x01\n\x08Register\x12\x41.tunix.experimental.distributed.runtime.discovery.RegisterRequest\x1a\x42.tunix.experimental.distributed.runtime.discovery.RegisterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tunix.experimental.distributed.runtime.discovery.discovery_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=126
  _globals['_REGISTERREQUEST']._serialized_end=193
  _globals['_REGISTERRESPONSE']._serialized_start=195
  _globals['_REGISTERRESPONSE']._serialized_end=213
  _globals['_DISCOVERYSERVICE']._serialized_start=216
  _globals['_DISCOVERYSERVICE']._serialized_end=382
# @@protoc_insertion_point(module_scope)
